**Create a NumPy array with values from 1 to 10 and print it.**

In [ ]:
import numpy as np

arr = np.arange(1, 11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


**Create a 3x3 matrix with values ranging from 0 to 8.**

In [ ]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Create a 2x2 identity matrix.**

In [ ]:
import numpy as np

identity_matrix = np.eye(2)
print(identity_matrix)


[[1. 0.]
 [0. 1.]]


**Create a NumPy array with random values and find the mean, median, and standard deviation.**

In [ ]:
import numpy as np

random_array = np.random.rand(5)
mean_value = np.mean(random_array)
median_value = np.median(random_array)
std_deviation = np.std(random_array)

print("Array:", random_array)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)


Array: [0.14967417 0.81186229 0.21709887 0.84533981 0.47083675]
Mean: 0.4989623760620729
Median: 0.4708367461509174
Standard Deviation: 0.2898703215570255


**Perform element-wise addition of two NumPy arrays.**

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = array1 + array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Result:", result)


Array 1: [1 2 3]
Array 2: [4 5 6]
Result: [5 7 9]


**Create a NumPy array and reshape it to a 2x3 matrix.**

In [ ]:
import numpy as np

original_array = np.arange(6)
reshaped_matrix = original_array.reshape(2, 3)

print("Original Array:", original_array)
print("Reshaped Matrix:")
print(reshaped_matrix)


Original Array: [0 1 2 3 4 5]
Reshaped Matrix:
[[0 1 2]
 [3 4 5]]


**Calculate the dot product of two NumPy arrays.**

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
dot_product = np.dot(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Dot Product:", dot_product)


Array 1: [1 2 3]
Array 2: [4 5 6]
Dot Product: 32


**Matrix Multiplication:**

In [ ]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)
print("Matrix Multiplication Result:")
print(result)


Matrix Multiplication Result:
[[19 22]
 [43 50]]


**Transpose of a Matrix:**

In [ ]:
import numpy as np

original_matrix = np.array([[1, 2, 3], [4, 5, 6]])
transpose_matrix = np.transpose(original_matrix)

print("Original Matrix:")
print(original_matrix)
print("Transposed Matrix:")
print(transpose_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]]
Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


**Element-wise Logarithm:**

In [ ]:
import numpy as np

original_array = np.array([1, 10, 100])
log_values = np.log(original_array)

print("Original Array:")
print(original_array)
print("Element-wise Logarithm:")
print(log_values)


Original Array:
[  1  10 100]
Element-wise Logarithm:
[0.         2.30258509 4.60517019]


**Statistical Operations on a Matrix:**

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
mean_value = np.mean(matrix)
std_deviation = np.std(matrix, axis=1)

print("Matrix:")
print(matrix)
print("Mean of Matrix:", mean_value)
print("Standard Deviation along Axis 1:")
print(std_deviation)


Matrix:
[[1 2 3]
 [4 5 6]]
Mean of Matrix: 3.5
Standard Deviation along Axis 1:
[0.81649658 0.81649658]


 **Linear Regression:**

In [ ]:
import numpy as np

# Assuming data points (x, y)
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

# Perform linear regression
coefficients = np.polyfit(x, y, 1)

print("Linear Regression Coefficients:")
print(coefficients)


Linear Regression Coefficients:
[0.6 2.2]


**Finding Eigenvalues and Eigenvectors:**

In [ ]:
import numpy as np

matrix = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[3. 2.]
Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


 **Element-wise Sum Using Loop:**

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

result = np.zeros_like(array1)

for i in range(len(array1)):
    result[i] = array1[i] + array2[i]

print("Element-wise Sum Using Loop:")
print(result)


Element-wise Sum Using Loop:
[6 6 6 6 6]


**Matrix Multiplication with Loop:**

In [ ]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

rows, cols = matrix1.shape
result = np.zeros((rows, cols))

for i in range(rows):
    for j in range(cols):
        for k in range(cols):
            result[i][j] += matrix1[i][k] * matrix2[k][j]

print("Matrix Multiplication with Loop:")
print(result)


Matrix Multiplication with Loop:
[[19. 22.]
 [43. 50.]]


**Cumulative Sum Along Axis with Loop:**

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])

rows, cols = matrix.shape
cumulative_sum = np.zeros_like(matrix)

for i in range(rows):
    sum_val = 0
    for j in range(cols):
        sum_val += matrix[i][j]
        cumulative_sum[i][j] = sum_val

print("Cumulative Sum Along Axis with Loop:")
print(cumulative_sum)


Cumulative Sum Along Axis with Loop:
[[ 1  3  6]
 [ 4  9 15]]


**Element-wise Product Using Loop:**

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

result = np.zeros_like(array1)

for i in range(len(array1)):
    result[i] = array1[i] * array2[i]

print("Element-wise Product Using Loop:")
print(result)


Element-wise Product Using Loop:
[5 8 9 8 5]


**odd even program using numpy**

In [ ]:
import numpy as np

# Example input array
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Check odd/even without function
result = np.where(numbers % 2 == 0, 'Even', 'Odd')

# Display result
print("Original Array:", numbers)
print("Odd/Even Status:", result)


Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Odd/Even Status: ['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


**In this example, the program prompts the user to enter the size of the array and the elements of the array. It then converts the user input into a NumPy array and performs a simple operation (squaring each element). Finally, it displays the original and squared arrays.**

In [ ]:
import numpy as np

# Get the size of the array from the user
array_size = int(input("Enter the size of the array: "))

# Get array elements from the user
user_array = []
for i in range(array_size):
    element = float(input(f"Enter element {i + 1}: "))
    user_array.append(element)

# Convert the list to a NumPy array
numpy_array = np.array(user_array)

# Display the original array
print("Original Array:", numpy_array)

# Perform some NumPy operations (e.g., square each element)
squared_array = np.square(numpy_array)

# Display the result
print("Squared Array:", squared_array)


Enter the size of the array: 5
Enter element 1: 3
Enter element 2: 7
Enter element 3: 9
Enter element 4: 2
Enter element 5: 4
Original Array: [3. 7. 9. 2. 4.]
Squared Array: [ 9. 49. 81.  4. 16.]


**In this program, the user is prompted to enter the dimensions of a matrix, and then the elements of the matrix. The program then performs a matrix operation (element-wise squaring in this case) using NumPy**

In [ ]:
import numpy as np

# Get the dimensions of the matrix from the user
rows = int(input("Enter the number of rows for the matrix: "))
columns = int(input("Enter the number of columns for the matrix: "))

# Get the elements of the matrix from the user
matrix_elements = []
for i in range(rows):
    row = []
    for j in range(columns):
        element = float(input(f"Enter element at position ({i + 1}, {j + 1}): "))
        row.append(element)
    matrix_elements.append(row)

# Create a NumPy array from the user-input matrix
matrix = np.array(matrix_elements)

# Perform a NumPy operation (e.g., element-wise squaring)
result = np.square(matrix)

# Display the original matrix and the result
print("\nOriginal Matrix:")
print(matrix)

print("\nResult (Element-wise Squaring):")
print(result)


Enter the number of rows for the matrix: 2
Enter the number of columns for the matrix: 3
Enter element at position (1, 1): 3
Enter element at position (1, 2): 2
Enter element at position (1, 3): 5
Enter element at position (2, 1): 6
Enter element at position (2, 2): 3
Enter element at position (2, 3): 2

Original Matrix:
[[3. 2. 5.]
 [6. 3. 2.]]

Result (Element-wise Squaring):
[[ 9.  4. 25.]
 [36.  9.  4.]]


**Prime Numbers in a Range**

In [ ]:
import numpy as np

# Input range from the user
start_range = int(input("Enter the start of the range: "))
end_range = int(input("Enter the end of the range: "))

# Find and display prime numbers in the given range
result_primes = np.extract([np.all(i % np.arange(2, int(np.sqrt(i)) + 1) != 0) for i in range(start_range, end_range + 1)],
                           np.arange(start_range, end_range + 1))
print("Prime numbers in the range:", result_primes)


Enter the start of the range: 10
Enter the end of the range: 20
Prime numbers in the range: [11 13 17 19]


**Fibonacci Series**

In [ ]:
import numpy as np

# Input limit from the user
fib_limit = int(input("Enter the limit for Fibonacci series: "))

# Generate and display the Fibonacci series up to the specified limit
fib_series = [0, 1]
while fib_series[-1] + fib_series[-2] <= fib_limit:
    fib_series.append(fib_series[-1] + fib_series[-2])

result_fibonacci = np.array(fib_series)
print("Fibonacci series up to {}: {}".format(fib_limit, result_fibonacci))


Enter the limit for Fibonacci series: 10
Fibonacci series up to 10: [0 1 1 2 3 5 8]


**Sorting an Array**

In [ ]:
import numpy as np

# Input array from the user
input_array = np.array(eval(input("Enter an array of integers: ")))

# Sort the array
sorted_array = np.sort(input_array)

# Display the sorted array
print("Sorted Array:", sorted_array)


Enter an array of integers: 3,8,9,2,0
Sorted Array: [0 2 3 8 9]
